name: Upload Hyper Commander Script

on:
  push:
    paths:
      - 'hyper_commander.sh'

jobs:
  upload-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'RafaelKarcz'
        git config --global user.email 'rafael.karcz@gmail.com'
        git add .
        git commit -m "Automated commit for hyper_commander.sh changes" || echo "No changes to commit"
        git push --quiet https://${{ secrets.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 }}@github.com/RafaelKarcz/HyperCommander.git
